# Dockerfile.dev
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Dùng polling để hot reload trong Docker hoạt động
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
